camera_id: 1
imgsz: 640
conf: 0.25
iou: 0.5
camera_backend: auto
target_class: sports ball
mqtt:
  host: 127.0.0.1
  port: 1883
  topic: tracker/ball
log_level: INFO
influx:
  enabled: true
  url: http://localhost:8086
  org: Berufskolleg
  bucket: Tracking
  token: ""   # Empfehlung: leer lassen und stattdessen INFLUX_TOKEN als Umgebungsvariable setzen
